spring.application.name=proyecto-entidades

spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=d19355557d02be3e296f2764274f12e0c54d080096af8df05f21dfaac2158a02
spring.datasource.password=sk_h9xCtHt0WR_9O9AXNSUkn
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Cambia el nivel global a solo Advertencias y Errores
logging.level.root=WARN