spring.application.name=proyecto-entidades

spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=4e81900879083c86e6dd0e9443d3b3a0ff00310b660632bab865a837b0b59e14
spring.datasource.password=sk_MbeYEOsvRxUk_PHvD1qcE
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Cambia el nivel global a solo Advertencias y Errores
logging.level.root=WARN